version: "3.8"
name: "wild-workout-microservice"

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"