// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrainingBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainingBalanceRequest) Reset() {
	*x = GetTrainingBalanceRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingBalanceRequest) ProtoMessage() {}

func (x *GetTrainingBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetTrainingBalanceRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrainingBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTrainingBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainingBalanceResponse) Reset() {
	*x = GetTrainingBalanceResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingBalanceResponse) ProtoMessage() {}

func (x *GetTrainingBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetTrainingBalanceResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrainingBalanceResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateTrainingBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountChange  int64                  `protobuf:"varint,2,opt,name=amount_change,json=amountChange,proto3" json:"amount_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrainingBalanceRequest) Reset() {
	*x = UpdateTrainingBalanceRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrainingBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainingBalanceRequest) ProtoMessage() {}

func (x *UpdateTrainingBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainingBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrainingBalanceRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTrainingBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTrainingBalanceRequest) GetAmountChange() int64 {
	if x != nil {
		return x.AmountChange
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05users\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x19GetTrainingBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x1aGetTrainingBalanceResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\"\\\n" +
	"\x1cUpdateTrainingBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\ramount_change\x18\x02 \x01(\x03R\famountChange2\xc3\x01\n" +
	"\fUsersService\x12[\n" +
	"\x12GetTrainingBalance\x12 .users.GetTrainingBalanceRequest\x1a!.users.GetTrainingBalanceResponse\"\x00\x12V\n" +
	"\x15UpdateTrainingBalance\x12#.users.UpdateTrainingBalanceRequest\x1a\x16.google.protobuf.Empty\"\x00BFZDgithub.com/ThreeDotsLabs/wild-workouts-go-ddd-example/internal/usersb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_proto_goTypes = []any{
	(*GetTrainingBalanceRequest)(nil),    // 0: users.GetTrainingBalanceRequest
	(*GetTrainingBalanceResponse)(nil),   // 1: users.GetTrainingBalanceResponse
	(*UpdateTrainingBalanceRequest)(nil), // 2: users.UpdateTrainingBalanceRequest
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	0, // 0: users.UsersService.GetTrainingBalance:input_type -> users.GetTrainingBalanceRequest
	2, // 1: users.UsersService.UpdateTrainingBalance:input_type -> users.UpdateTrainingBalanceRequest
	1, // 2: users.UsersService.GetTrainingBalance:output_type -> users.GetTrainingBalanceResponse
	3, // 3: users.UsersService.UpdateTrainingBalance:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
