name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Create and push major version tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump major version
        id: bump
        run: |
          OLD_TAG=${{ steps.get_tag.outputs.tag }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${OLD_TAG#v}"
          NEW_MAJOR=$((MAJOR + 1))
          NEW_TAG="v${NEW_MAJOR}.0.0"
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          
      - name: Create and push tag using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git tag ${{ steps.bump.outputs.new_tag }}
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin ${{ steps.bump.outputs.new_tag }}
